language: php

php:
  - 5.6
  - 5.5
  - 5.4

before_install:
  - sudo apt-get install php5-dev libpcre3-dev gcc make php5-mysql
  - git clone --depth=1 git://github.com/phalcon/cphalcon.git
  - cd cphalcon/build
  - sudo ./install
  - cd ../..
  - phpenv config-add travis.php.ini

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c travis.phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v